root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - ./src/tsconfig.json
plugins:
  - "@typescript-eslint"
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - prettier
env:
  es6: true
  node: true
