# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: cimg/node:lts
      - image: circleci/postgres:13-ram
    working_directory: ~/mocha-slonik
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run:
          name: Compile TypeScript
          command: npm run build
      - run:
          name: Run tests
          command: npm test
          environment:
            DATABASE_URL: postgres://postgres@localhost:5432/circle_test
  build:
    docker:
      - image: cimg/node:lts
    working_directory: ~/mocha-slonik
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run:
          name: Build package
          command: |
            mkdir package
            npm pack --pack-destination package
      - persist_to_workspace:
          root: .
          paths:
            - "*"
      - store_artifacts:
          path: package
          destination: .
  publish:
    docker:
      - image: cimg/node:lts
    working_directory: ~/mocha-slonik
    steps:
      - attach_workspace:
          at: ~/mocha-slonik
      - run:
          name: Set NPM token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run: npm publish
      - unless:
          condition: << pipeline.git.tag >>
          steps:
            - run: npm publish --dry-run

workflows:
  build-and-publish:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          context: npm
          requires:
            - build
          filters:
            branches:
              only: master
